plugins:
  - jekyll-archives
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

title: "Bits, Bytes & Neural Networks"
subtitle: "A Data Scientist's Digital Playground"
email: aldente0630@gmail.com
name: aldente0630
description: >
  A tech blog focusing on AI/ML paper reviews and latest research trends
baseurl: ""
url: "https://aldente0630.github.io"
cover: "/assets/my_header_image.jpg"
logo: "/assets/my_logo.png"

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true
  trail:
    before: 2
    after: 2 

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

descriptions:
  - cat: computer-vision
    desc: "Posts about Computer Vision research papers and techniques"
  - cat: natural-language-processing
    desc: "Posts about Natural Language Processing research papers and techniques"

social:
  - name: Facebook
    icon: facebook
    username: aldente0630
    url: "https://www.facebook.com/aldente0630"
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: aldente0630
    url: https://github.com/aldente0630
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Jonas Kim
    url: https://www.linkedin.com/in/aldente0630
    desc: Connect with me on LinkedIn
    share: true

protocols:
    fb_image: "/assets/my_logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/my_logo.png"

    os_repo: "https://github.com/aldente0630/aldente0630.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:aldente0630/aldente0630.github.io.git"
